use_frameworks!

platform :ios, '8.0'

target 'GGPodStudyModule2_Example' do
  pod 'GGPodStudyModule2', :path => '../'

  target 'GGPodStudyModule2_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
